meta:
  schema-version: 0.1.0
  created-on: "2026-03-02T16:13:51Z"
  cli-version: 0.3.282
projects:
  jfrog-maven-demo:
    targets:
      - pom.xml
    manager:
      ecosystem: java
      name: maven
      version: ""
    overrides:
      org.yaml:snakeyaml:
        "1.33":
          use: 1.33+sp1
        "1.30":
          use: 1.30+sp1
      com.fasterxml.jackson.core:jackson-databind:
        2.13.1:
          use: 2.13.1+sp1
      org.apache.commons:commons-text:
        "1.9":
          use: 1.9+sp1
      org.springframework:spring-core:
        5.3.26:
          use: 5.3.26+sp1
      org.springframework:spring-web:
        5.3.26:
          use: 5.3.26+sp1
      com.fasterxml.jackson.core:jackson-core:
        2.13.4:
          use: 2.13.4+sp2
      net.minidev:json-smart:
        2.4.8:
          use: 2.4.8+sp1
      org.apache.commons:commons-lang3:
        3.12.0:
          use: 3.12.0+sp1
      org.springframework.boot:spring-boot:
        2.7.18:
          use: 2.7.18+sp1
      org.apache.logging.log4j:log4j-core:
        2.14.1:
          use: 2.14.1+sp3
      org.springframework:spring-webmvc:
        5.3.25:
          use: 5.3.25+sp1
      commons-io:commons-io:
        "2.6":
          use: 2.6+sp1
      commons-beanutils:commons-beanutils:
        1.9.4:
          use: 1.9.4+sp1
