spring.application.name=seal-jfrog-maven-demo
server.port=8080

logging.level.root=INFO
logging.level.io.sealsecurity.demo=DEBUG

spring.jackson.serialization.indent-output=true

management.endpoints.web.exposure.include=health,info
